# Generated by Django 6.1.1 on 2026-09-19 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nitrogen", models.FloatField()),
                ("phosphorus", models.FloatField()),
                ("potassium", models.FloatField()),
                ("ph", models.FloatField()),
                ("moisture", models.FloatField()),
                ("soil_type", models.CharField(max_length=60)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("rainfall", models.FloatField()),
                ("region", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=60)),
                ("irrigation_type", models.CharField(max_length=60)),
                ("crop", models.CharField(max_length=100)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="fallback", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["farmer", "created_at"],
                        name="crop_recomm_farmer__675943_idx",
                    )
                ],
            },
        ),
    ]
