# Generated by Django 6.1.1 on 2026-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField()),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank for all-India schemes",
                        max_length=100,
                    ),
                ),
                ("eligibility", models.TextField()),
                ("benefits", models.TextField()),
                ("official_url", models.URLField(blank=True)),
                ("category", models.CharField(blank=True, max_length=80)),
                (
                    "min_land_acres",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("crop", models.CharField(blank=True, max_length=100)),
                ("verified_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "category"],
                        name="schemes_sch_state_cd931a_idx",
                    )
                ],
            },
        ),
    ]
