# Generated by Django 6.1.1 on 2026-09-19 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seeds", "Seeds"),
                            ("fertilizer", "Fertilizer"),
                            ("pesticides", "Pesticides"),
                            ("labour", "Labour"),
                            ("irrigation", "Irrigation"),
                            ("machinery", "Machinery"),
                            ("transport", "Transport"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["farmer", "date"], name="expenses_ex_farmer__89ce6a_idx"
                    ),
                    models.Index(
                        fields=["farmer", "category"],
                        name="expenses_ex_farmer__776bd9_idx",
                    ),
                ],
            },
        ),
    ]
